modLoader="kotlinforforge"
loaderVersion="[5.5,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "cobblenav"
version = "${version}"
displayName = "Cobblenav"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.cobblenav]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblenav]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cobblenav.mixins.json"
