modLoader="kotlinforforge"
loaderVersion="[5.5,)"
#issueTrackerURL = ""
license = "MPL-2.0"

[[mods]]
modId = "cobblenav"
version = "${version}"
displayName = "Cobblenav"
authors = "gatekeep"
description = '''
Cobblenav (Cobblemon Pokenav) is a sidemod that adds a pokenav item similar to the one featured in the Pokemon RS games
'''
logoFile = "assets/cobblenav/logo.png"

[[dependencies.cobblenav]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblenav]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependecies.cobblenav]]
modId = "cobblemon"
type = "required"
versionRange = "[1.6.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cobblenav.mixins.json"
